/**
 * 글자 대비 게이트(`TemplatePaintGate.stories.tsx` 의 LabelContrastGate)가 이미 알고 있는 미달 목록.
 *
 * KAN-056 을 마칠 때 대상 템플릿 13개 × 카탈로그 가이드 30개에서 잰 값이다. 키는
 * `가이드 · fixture · text[문서 순서] "글자 앞 24자"`, 값은 그때의 대비(소수 둘째 자리)다.
 * 게이트는 이 목록에 없는 미달, 여기 적힌 값보다 0.01 넘게 떨어진 대비, 이제 기준을 넘어
 * 목록에서 지워야 할 항목을 모두 실패로 낸다. 목록은 줄어들기만 해야 한다.
 *
 * 원인은 대부분 KAN-056 전부터 있던 것이다 — Mindmap 노드의 불투명 팔레트 면, Requirement 의
 * 반투명 표기 글자(opacity 0.6·0.8)와 머리 띠, 일부 가이드의 shape.fill·edge.stroke 쌍.
 * ArchiMate 계층 면(팔레트 35%)은 KAN-056 검토 항목 2에서 받아들인 값이다.
 * 줄이는 일은 대비 후속 카드가 맡는다.
 */
export const LABEL_CONTRAST_BASELINE: Readonly<Record<string, number>> = {
  "minimal-line-01 · mindmap · text[0] \"Mindmap\"": 1,
  "minimal-line-01 · requirement · text[0] \"«requirement»\"": 4.2,
  "minimal-line-01 · requirement · text[3] \"«functionalRequirement»\"": 4.2,
  "colorful-flat-01 · mindmap · text[1] \"Topic A\"": 3.44,
  "colorful-flat-01 · mindmap · text[2] \"Topic B\"": 3.44,
  "colorful-flat-01 · mindmap · text[3] \"Topic C\"": 3.44,
  "colorful-flat-01 · mindmap · text[4] \"Topic D\"": 3.44,
  "colorful-flat-01 · requirement · text[0] \"«requirement»\"": 3.82,
  "colorful-flat-01 · requirement · text[3] \"«functionalRequirement»\"": 3.82,
  "ink-line-duotone-01 · mindmap · text[0] \"Mindmap\"": 2.7,
  "ink-line-duotone-01 · mindmap · text[1] \"Topic A\"": 2.89,
  "ink-line-duotone-01 · mindmap · text[2] \"Topic B\"": 2.89,
  "ink-line-duotone-01 · mindmap · text[3] \"Topic C\"": 2.89,
  "ink-line-duotone-01 · mindmap · text[4] \"Topic D\"": 2.89,
  "ink-line-duotone-01 · archimate-business · text[0] \"Customer\"": 4.37,
  "ink-line-duotone-01 · archimate-business · text[1] \"[role]\"": 4.37,
  "ink-line-duotone-01 · archimate-business · text[2] \"Order Proc\"": 4.37,
  "ink-line-duotone-01 · archimate-business · text[3] \"[process]\"": 4.37,
  "ink-line-duotone-01 · requirement · text[0] \"«requirement»\"": 2.81,
  "ink-line-duotone-01 · requirement · text[3] \"«functionalRequirement»\"": 2.81,
  "corporate-schematic-01 · mindmap · text[0] \"Mindmap\"": 1.82,
  "corporate-schematic-01 · mindmap · text[1] \"Topic A\"": 1.45,
  "corporate-schematic-01 · mindmap · text[2] \"Topic B\"": 1.45,
  "corporate-schematic-01 · mindmap · text[3] \"Topic C\"": 1.45,
  "corporate-schematic-01 · mindmap · text[4] \"Topic D\"": 1.45,
  "corporate-schematic-01 · requirement · text[0] \"«requirement»\"": 2.93,
  "corporate-schematic-01 · requirement · text[3] \"«functionalRequirement»\"": 2.93,
  "neon-gradient-dark-01 · block-diagram · text[0] \"Auth\"": 2.35,
  "neon-gradient-dark-01 · block-diagram · text[1] \"API\"": 2.35,
  "neon-gradient-dark-01 · block-diagram · text[2] \"Database\"": 2.35,
  "neon-gradient-dark-01 · mindmap · text[1] \"Topic A\"": 1.61,
  "neon-gradient-dark-01 · mindmap · text[2] \"Topic B\"": 1.61,
  "neon-gradient-dark-01 · mindmap · text[3] \"Topic C\"": 1.61,
  "neon-gradient-dark-01 · mindmap · text[4] \"Topic D\"": 1.61,
  "neon-gradient-dark-01 · kanban-board · text[3] \"Task A\"": 2.35,
  "neon-gradient-dark-01 · kanban-board · text[4] \"Task B\"": 2.35,
  "neon-gradient-dark-01 · kanban-board · text[5] \"Task C\"": 2.35,
  "neon-gradient-dark-01 · kanban-board · text[6] \"Task D\"": 2.35,
  "neon-gradient-dark-01 · architecture · text[2] \"Web Client\"": 2.35,
  "neon-gradient-dark-01 · architecture · text[3] \"API Server\"": 2.35,
  "neon-gradient-dark-01 · architecture · text[4] \"Database\"": 2.35,
  "neon-gradient-dark-01 · uml-component · text[0] \"OrderService\"": 2.35,
  "neon-gradient-dark-01 · uml-component · text[1] \"PaymentService\"": 2.35,
  "neon-gradient-dark-01 · bpmn · text[2] \"Process\"": 2.35,
  "neon-gradient-dark-01 · bpmn · text[3] \"Payment\"": 2.35,
  "neon-gradient-dark-01 · bpmn · text[4] \"Fulfil Order\"": 2.35,
  "neon-gradient-dark-01 · bpmn-collaboration · text[2] \"Place order\"": 2.35,
  "neon-gradient-dark-01 · bpmn-collaboration · text[3] \"Fulfil order\"": 2.35,
  "neon-gradient-dark-01 · c4-code · text[0] \"User\"": 2.35,
  "neon-gradient-dark-01 · c4-code · text[1] \"- id: string\"": 2.35,
  "neon-gradient-dark-01 · c4-code · text[2] \"+ login(): void\"": 2.35,
  "neon-gradient-dark-01 · c4-code · text[3] \"Account\"": 2.35,
  "neon-gradient-dark-01 · c4-code · text[4] \"- balance: number\"": 2.35,
  "neon-gradient-dark-01 · c4-code · text[5] \"+ deposit(n): void\"": 2.35,
  "neon-gradient-dark-01 · requirement · text[0] \"«requirement»\"": 1.81,
  "neon-gradient-dark-01 · requirement · text[1] \"Authenticate\"": 2.65,
  "neon-gradient-dark-01 · requirement · text[2] \"text: User must log in\"": 1.98,
  "neon-gradient-dark-01 · requirement · text[3] \"«functionalRequirement»\"": 1.81,
  "neon-gradient-dark-01 · requirement · text[4] \"Authorize\"": 2.65,
  "neon-gradient-dark-01 · requirement · text[5] \"text: Role-based access\"": 1.98,
  "neon-gradient-dark-01 · timeline · text[0] \"Phase 1\"": 2.35,
  "neon-gradient-dark-01 · timeline · text[2] \"Phase 2\"": 2.35,
  "neon-gradient-dark-01 · uml-deployment · text[1] \"Web Server\"": 2.35,
  "neon-gradient-dark-01 · uml-deployment · text[2] \"DB Server\"": 2.35,
  "marker-sketchnote-01 · mindmap · text[0] \"Mindmap\"": 3.9,
  "marker-sketchnote-01 · requirement · text[0] \"«requirement»\"": 3.76,
  "marker-sketchnote-01 · requirement · text[3] \"«functionalRequirement»\"": 3.76,
  "iso-color-block-01 · mindmap · text[0] \"Mindmap\"": 3.58,
  "iso-color-block-01 · mindmap · text[1] \"Topic A\"": 3.92,
  "iso-color-block-01 · mindmap · text[2] \"Topic B\"": 3.92,
  "iso-color-block-01 · mindmap · text[3] \"Topic C\"": 3.92,
  "iso-color-block-01 · mindmap · text[4] \"Topic D\"": 3.92,
  "iso-color-block-01 · requirement · text[0] \"«requirement»\"": 2.46,
  "iso-color-block-01 · requirement · text[2] \"text: User must log in\"": 3.84,
  "iso-color-block-01 · requirement · text[3] \"«functionalRequirement»\"": 2.46,
  "iso-color-block-01 · requirement · text[5] \"text: Role-based access\"": 3.84,
  "swiss-systematic-01 · mindmap · text[0] \"Mindmap\"": 1.39,
  "swiss-systematic-01 · mindmap · text[1] \"Topic A\"": 3.78,
  "swiss-systematic-01 · mindmap · text[2] \"Topic B\"": 3.78,
  "swiss-systematic-01 · mindmap · text[3] \"Topic C\"": 3.78,
  "swiss-systematic-01 · mindmap · text[4] \"Topic D\"": 3.78,
  "terminal-ascii-01 · mindmap · text[0] \"Mindmap\"": 1.09,
  "terminal-ascii-01 · mindmap · text[1] \"Topic A\"": 1.33,
  "terminal-ascii-01 · mindmap · text[2] \"Topic B\"": 1.33,
  "terminal-ascii-01 · mindmap · text[3] \"Topic C\"": 1.33,
  "terminal-ascii-01 · mindmap · text[4] \"Topic D\"": 1.33,
  "terminal-ascii-01 · requirement · text[0] \"«requirement»\"": 4.47,
  "terminal-ascii-01 · requirement · text[3] \"«functionalRequirement»\"": 4.47,
  "bauhaus-geometric-01 · requirement · text[0] \"«requirement»\"": 4.37,
  "bauhaus-geometric-01 · requirement · text[3] \"«functionalRequirement»\"": 4.37,
  "riso-print-01 · mindmap · text[0] \"Mindmap\"": 1,
  "riso-print-01 · mindmap · text[1] \"Topic A\"": 4.23,
  "riso-print-01 · mindmap · text[2] \"Topic B\"": 4.23,
  "riso-print-01 · mindmap · text[3] \"Topic C\"": 4.23,
  "riso-print-01 · mindmap · text[4] \"Topic D\"": 4.23,
  "riso-print-01 · kanban-board · text[3] \"Task A\"": 4.48,
  "riso-print-01 · kanban-board · text[4] \"Task B\"": 4.48,
  "riso-print-01 · kanban-board · text[5] \"Task C\"": 4.48,
  "riso-print-01 · kanban-board · text[6] \"Task D\"": 4.48,
  "riso-print-01 · bpmn · text[2] \"Process\"": 4.4,
  "riso-print-01 · bpmn · text[3] \"Payment\"": 4.4,
  "riso-print-01 · bpmn · text[4] \"Fulfil Order\"": 4.4,
  "riso-print-01 · archimate-business · text[0] \"Customer\"": 3.92,
  "riso-print-01 · archimate-business · text[1] \"[role]\"": 3.92,
  "riso-print-01 · archimate-business · text[2] \"Order Proc\"": 3.92,
  "riso-print-01 · archimate-business · text[3] \"[process]\"": 3.92,
  "riso-print-01 · bpmn-collaboration · text[2] \"Place order\"": 4.4,
  "riso-print-01 · bpmn-collaboration · text[3] \"Fulfil order\"": 4.4,
  "riso-print-01 · requirement · text[0] \"«requirement»\"": 2.29,
  "riso-print-01 · requirement · text[1] \"Authenticate\"": 4.09,
  "riso-print-01 · requirement · text[2] \"text: User must log in\"": 3.38,
  "riso-print-01 · requirement · text[3] \"«functionalRequirement»\"": 2.29,
  "riso-print-01 · requirement · text[4] \"Authorize\"": 4.09,
  "riso-print-01 · requirement · text[5] \"text: Role-based access\"": 3.38,
  "hud-telemetry-01 · mindmap · text[0] \"Mindmap\"": 1.08,
  "hud-telemetry-01 · mindmap · text[1] \"Topic A\"": 1.45,
  "hud-telemetry-01 · mindmap · text[2] \"Topic B\"": 1.45,
  "hud-telemetry-01 · mindmap · text[3] \"Topic C\"": 1.45,
  "hud-telemetry-01 · mindmap · text[4] \"Topic D\"": 1.45,
  "hud-telemetry-01 · requirement · text[0] \"«requirement»\"": 4.41,
  "hud-telemetry-01 · requirement · text[3] \"«functionalRequirement»\"": 4.41,
  "halftone-print-01 · mindmap · text[0] \"Mindmap\"": 3.76,
  "halftone-print-01 · mindmap · text[1] \"Topic A\"": 2.29,
  "halftone-print-01 · mindmap · text[2] \"Topic B\"": 2.29,
  "halftone-print-01 · mindmap · text[3] \"Topic C\"": 2.29,
  "halftone-print-01 · mindmap · text[4] \"Topic D\"": 2.29,
  "halftone-print-01 · requirement · text[0] \"«requirement»\"": 4.2,
  "halftone-print-01 · requirement · text[3] \"«functionalRequirement»\"": 4.2,
  "glitch-duotone-01 · requirement · text[0] \"«requirement»\"": 3.91,
  "glitch-duotone-01 · requirement · text[3] \"«functionalRequirement»\"": 3.91,
  "neumorphic-soft-01 · mindmap · text[1] \"Topic A\"": 2.77,
  "neumorphic-soft-01 · mindmap · text[2] \"Topic B\"": 2.77,
  "neumorphic-soft-01 · mindmap · text[3] \"Topic C\"": 2.77,
  "neumorphic-soft-01 · mindmap · text[4] \"Topic D\"": 2.77,
  "neumorphic-soft-01 · requirement · text[0] \"«requirement»\"": 3.33,
  "neumorphic-soft-01 · requirement · text[3] \"«functionalRequirement»\"": 3.33,
  "clay-playful-01 · requirement · text[0] \"«requirement»\"": 3.19,
  "clay-playful-01 · requirement · text[3] \"«functionalRequirement»\"": 3.19,
  "kawaii-pastel-01 · requirement · text[0] \"«requirement»\"": 3.07,
  "kawaii-pastel-01 · requirement · text[3] \"«functionalRequirement»\"": 3.07,
  "editorial-data-01 · mindmap · text[0] \"Mindmap\"": 2.07,
  "editorial-data-01 · mindmap · text[1] \"Topic A\"": 3.2,
  "editorial-data-01 · mindmap · text[2] \"Topic B\"": 3.2,
  "editorial-data-01 · mindmap · text[3] \"Topic C\"": 3.2,
  "editorial-data-01 · mindmap · text[4] \"Topic D\"": 3.2,
  "editorial-data-01 · requirement · text[0] \"«requirement»\"": 4.05,
  "editorial-data-01 · requirement · text[3] \"«functionalRequirement»\"": 4.05,
  "memphis-pattern-01 · requirement · text[0] \"«requirement»\"": 3.48,
  "memphis-pattern-01 · requirement · text[3] \"«functionalRequirement»\"": 3.48,
  "retro70s-warm-01 · mindmap · text[0] \"Mindmap\"": 3.42,
  "retro70s-warm-01 · mindmap · text[1] \"Topic A\"": 2.99,
  "retro70s-warm-01 · mindmap · text[2] \"Topic B\"": 2.99,
  "retro70s-warm-01 · mindmap · text[3] \"Topic C\"": 2.99,
  "retro70s-warm-01 · mindmap · text[4] \"Topic D\"": 2.99,
  "retro70s-warm-01 · requirement · text[0] \"«requirement»\"": 3.28,
  "retro70s-warm-01 · requirement · text[3] \"«functionalRequirement»\"": 3.28,
  "dopamine-max-01 · mindmap · text[0] \"Mindmap\"": 4.26,
  "dopamine-max-01 · mindmap · text[1] \"Topic A\"": 3.76,
  "dopamine-max-01 · mindmap · text[2] \"Topic B\"": 3.76,
  "dopamine-max-01 · mindmap · text[3] \"Topic C\"": 3.76,
  "dopamine-max-01 · mindmap · text[4] \"Topic D\"": 3.76,
  "dopamine-max-01 · requirement · text[0] \"«requirement»\"": 4.21,
  "dopamine-max-01 · requirement · text[3] \"«functionalRequirement»\"": 4.21,
  "bento-stat-01 · mindmap · text[0] \"Mindmap\"": 1,
  "bento-stat-01 · requirement · text[0] \"«requirement»\"": 4.01,
  "bento-stat-01 · requirement · text[3] \"«functionalRequirement»\"": 4.01,
  "synthwave-01 · mindmap · text[0] \"Mindmap\"": 1,
  "synthwave-01 · mindmap · text[1] \"Topic A\"": 1.4,
  "synthwave-01 · mindmap · text[2] \"Topic B\"": 1.4,
  "synthwave-01 · mindmap · text[3] \"Topic C\"": 1.4,
  "synthwave-01 · mindmap · text[4] \"Topic D\"": 1.4,
  "synthwave-01 · requirement · text[0] \"«requirement»\"": 3.88,
  "synthwave-01 · requirement · text[3] \"«functionalRequirement»\"": 3.88,
  "artdeco-luxe-01 · mindmap · text[1] \"Topic A\"": 2.07,
  "artdeco-luxe-01 · mindmap · text[2] \"Topic B\"": 2.07,
  "artdeco-luxe-01 · mindmap · text[3] \"Topic C\"": 2.07,
  "artdeco-luxe-01 · mindmap · text[4] \"Topic D\"": 2.07,
  "artdeco-luxe-01 · requirement · text[0] \"«requirement»\"": 3.45,
  "artdeco-luxe-01 · requirement · text[3] \"«functionalRequirement»\"": 3.45,
  "darkluxe-01 · mindmap · text[0] \"Mindmap\"": 1.91,
  "darkluxe-01 · mindmap · text[1] \"Topic A\"": 3.49,
  "darkluxe-01 · mindmap · text[2] \"Topic B\"": 3.49,
  "darkluxe-01 · mindmap · text[3] \"Topic C\"": 3.49,
  "darkluxe-01 · mindmap · text[4] \"Topic D\"": 3.49,
  "darkluxe-01 · archimate-business · text[0] \"Customer\"": 3.65,
  "darkluxe-01 · archimate-business · text[1] \"[role]\"": 3.65,
  "darkluxe-01 · archimate-business · text[2] \"Order Proc\"": 3.65,
  "darkluxe-01 · archimate-business · text[3] \"[process]\"": 3.65,
  "darkluxe-01 · requirement · text[0] \"«requirement»\"": 3.5,
  "darkluxe-01 · requirement · text[3] \"«functionalRequirement»\"": 3.5,
  "organic-blob-01 · requirement · text[0] \"«requirement»\"": 3.11,
  "organic-blob-01 · requirement · text[3] \"«functionalRequirement»\"": 3.11,
  "ukiyoe-flat-01 · mindmap · text[1] \"Topic A\"": 2.82,
  "ukiyoe-flat-01 · mindmap · text[2] \"Topic B\"": 2.82,
  "ukiyoe-flat-01 · mindmap · text[3] \"Topic C\"": 2.82,
  "ukiyoe-flat-01 · mindmap · text[4] \"Topic D\"": 2.82,
  "ukiyoe-flat-01 · requirement · text[0] \"«requirement»\"": 3.8,
  "ukiyoe-flat-01 · requirement · text[3] \"«functionalRequirement»\"": 3.8,
  "pixel-retro-01 · mindmap · text[1] \"Topic A\"": 3.6,
  "pixel-retro-01 · mindmap · text[2] \"Topic B\"": 3.6,
  "pixel-retro-01 · mindmap · text[3] \"Topic C\"": 3.6,
  "pixel-retro-01 · mindmap · text[4] \"Topic D\"": 3.6,
  "pixel-retro-01 · requirement · text[0] \"«requirement»\"": 3.77,
  "pixel-retro-01 · requirement · text[3] \"«functionalRequirement»\"": 3.77,
};
