/**
 * vizTypeRegistry — 유형 축 코드 SSOT (KAN-020, 전량 backfill KAN-040).
 *
 * `visualization-type-inventory.md` §5(VT 행)/§6(export 매핑)의 **채택 87 유형**을 코드 슬롯으로 전사한다.
 * 각 엔트리는 `id/name/exportNames/kind` 슬롯 정체성 + rich `meta`(`VizTypeMeta`)를 가진다 — KAN-040으로
 * pending 81종을 전량 backfill해 **전 엔트리 authored**(pending 0). ⛔ 범위외 3행(VT-520/610/611, 컴포넌트
 * 없음)은 제외한다.
 *
 * **순수 데이터**(컴포넌트 import 없음): exportNames는 문자열이다. export 존재성·커버리지는 registry.test.ts가
 * `templates/index.ts`·`patterns/index.ts` 정적 스캔으로 양방향 검증하고, meta 완전성(전량 authored·통제 어휘·
 * related 정합성)도 registry.test.ts가 게이트한다('type-meta 필수' 승격, KAN-040).
 *
 * meta는 인벤토리 §5 각 행("한 줄 정의·대표 용도·프리미티브·aliases·tags·related")을 통제 어휘 union으로
 * 정규화해 승격한 것이다(free string 금지). ✅ 구현 유형이라 priority는 생략한다.
 *
 * 참고: geometry 트랙 `IsometricScene`(KAN-028)·G6 조합 프레임 `Kruchten4Plus1View`·`ViewpointFrame`(KAN-015)은
 * inventory §8-b가 VT 유형 행으로 미승격한 export라 여기 포함하지 않는다(registry.test allowlist에 문서화).
 */
import type { VizTypeRegistryEntry } from './types';

export const vizTypeRegistry: readonly VizTypeRegistryEntry[] = [
  // ── A. 엔지니어링/소프트웨어 다이어그램 (VT-1xx) ──────────────────────────────
  {
    id: 'VT-101',
    name: 'UML Class Diagram',
    exportNames: ['ClassDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '클래스·속성·연산과 관계 구조',
      dataShape: ['hierarchy', 'relationship'],
      primitives: ['node', 'edge', 'tree'],
      aliases: ['object diagram', 'C4 code-level class'],
      useWhen: [
        '도메인/코드 모델의 클래스 구조를 표현할 때',
        '상속·연관·의존 관계를 명세할 때',
      ],
      avoidWhen: [
        '런타임 시간순 상호작용이 핵심이면 Sequence(VT-108) 사용',
        '물리 배포 구성이면 Deployment(VT-104) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-112'],
    },
  },
  {
    id: 'VT-102',
    name: 'UML Package Diagram',
    exportNames: ['UMLPackageDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '패키지 그룹화와 의존 관계',
      dataShape: ['hierarchy', 'relationship'],
      primitives: ['node', 'edge', 'boundary'],
      aliases: [],
      useWhen: [
        '모듈/패키지 그룹의 구조를 정리할 때',
        '패키지 간 의존 관계를 관리할 때',
      ],
      avoidWhen: [
        '클래스 내부 구조는 Class(VT-101) 사용',
        '물리 배포는 Deployment(VT-104) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-101'],
    },
  },
  {
    id: 'VT-103',
    name: 'UML Component Diagram',
    exportNames: ['UMLComponentDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '컴포넌트·인터페이스 배선',
      dataShape: ['relationship', 'network'],
      primitives: ['node', 'edge', 'port'],
      aliases: ['composite structure diagram'],
      useWhen: [
        '컴포넌트와 제공/요구 인터페이스 배선을 표현할 때',
        '모듈 아키텍처를 명세할 때',
      ],
      avoidWhen: [
        '런타임 배치는 Deployment(VT-104) 사용',
        '클래스 상세는 Class(VT-101) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-104', 'VT-101'],
    },
  },
  {
    id: 'VT-104',
    name: 'UML Deployment Diagram',
    exportNames: ['UMLDeploymentDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '아티팩트의 실행 노드 배치',
      dataShape: ['relationship', 'hierarchy'],
      primitives: ['node', 'edge', 'boundary'],
      aliases: ['C4 deployment'],
      useWhen: [
        '소프트웨어 아티팩트의 물리/실행 노드 배치를 표현할 때',
        '인프라 배포 구성을 소통할 때',
      ],
      avoidWhen: [
        '논리 컴포넌트 배선은 Component(VT-103) 사용',
        '클라우드 서비스 구성은 Cloud Architecture(VT-115) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-103', 'VT-115'],
    },
  },
  {
    id: 'VT-105',
    name: 'UML Use Case Diagram',
    exportNames: ['UseCaseDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '액터-유스케이스 기능 관계',
      dataShape: ['relationship'],
      primitives: ['node', 'edge', 'boundary'],
      aliases: ['usecase'],
      useWhen: [
        '액터와 시스템 기능(유스케이스) 관계를 정의할 때',
        '요구 범위를 합의할 때',
      ],
      avoidWhen: [
        '내부 절차 흐름은 Activity(VT-106) 사용',
        '요구 추적성은 Requirement(VT-118) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-106', 'VT-118'],
    },
  },
  {
    id: 'VT-106',
    name: 'UML Activity Diagram',
    exportNames: ['ActivityDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '제어 흐름·병행·레인 절차 모델',
      dataShape: ['process'],
      primitives: ['node', 'edge', 'lane'],
      aliases: ['swimlane diagram', 'activity'],
      useWhen: [
        '제어 흐름과 병행·분기가 있는 절차를 모델링할 때',
        '스윔레인으로 담당 주체를 구분할 때',
      ],
      avoidWhen: [
        '범용 도식은 Flowchart(VT-201) 사용',
        '참여자 간 메시지 순서는 Sequence(VT-108) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-201'],
    },
  },
  {
    id: 'VT-107',
    name: 'UML State Machine',
    exportNames: ['StateDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '상태·이벤트 전이 모델',
      dataShape: ['process'],
      primitives: ['node', 'edge'],
      aliases: ['statechart', 'stateDiagram-v2'],
      useWhen: [
        '객체/프로토콜의 상태와 이벤트 전이를 모델링할 때',
        '수명주기 상태를 명세할 때',
      ],
      avoidWhen: [
        '시간순 메시지 교환은 Sequence(VT-108) 사용',
        '제어 흐름 절차는 Activity(VT-106) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-108', 'VT-106'],
    },
  },
  {
    id: 'VT-108',
    name: 'UML Sequence Diagram',
    // 다-export 유형: UML 상호작용 4종 투영을 3 export가 실현.
    exportNames: ['SequenceDiagram', 'UMLSequenceDiagram', 'ZenUMLDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '수명선 간 시간순 메시지 교환',
      dataShape: ['process', 'temporal'],
      primitives: ['lifeline', 'edge', 'lane'],
      aliases: ['communication', 'interaction overview', 'timing', 'ZenUML'],
      useWhen: [
        'API·시나리오의 시간순 상호작용을 설계할 때',
        '참여자 간 메시지 순서를 명세할 때',
        'ZenUML 텍스트 스타일이 필요하면 ZenUMLDiagram export 사용',
      ],
      avoidWhen: [
        '정적 클래스 구조는 Class(VT-101) 사용',
        '상태 전이는 State(VT-107) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-107'],
    },
  },
  {
    id: 'VT-109',
    name: 'C4 System Context',
    exportNames: ['C4ContextDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '시스템 블랙박스와 외부 관계',
      dataShape: ['relationship'],
      primitives: ['node', 'edge', 'boundary'],
      aliases: ['context diagram'],
      useWhen: [
        '시스템을 블랙박스로 두고 사용자·외부 시스템 관계를 표현할 때',
        '프로젝트 범위를 합의할 때',
      ],
      avoidWhen: [
        '내부 컨테이너 구성은 C4 Container(VT-110) 사용',
        '코드 수준 구조는 C4 Code(VT-112) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-110'],
    },
  },
  {
    id: 'VT-110',
    name: 'C4 Container',
    exportNames: ['C4ContainerDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '배포 단위(앱·DB)와 기술 구성',
      dataShape: ['relationship'],
      primitives: ['node', 'edge', 'boundary'],
      aliases: [],
      useWhen: ['시스템 내부의 배포 단위(앱·DB·서비스)와 기술 스택을 개관할 때'],
      avoidWhen: [
        '외부 범위 합의는 C4 Context(VT-109) 사용',
        '컨테이너 내부 컴포넌트는 C4 Component(VT-111) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-109', 'VT-111'],
    },
  },
  {
    id: 'VT-111',
    name: 'C4 Component',
    exportNames: ['C4ComponentDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '컨테이너 내부 컴포넌트 책임',
      dataShape: ['relationship'],
      primitives: ['node', 'edge', 'boundary'],
      aliases: [],
      useWhen: ['컨테이너 내부 컴포넌트의 책임과 상호작용을 상세화할 때'],
      avoidWhen: [
        '기술 스택 개관은 C4 Container(VT-110) 사용',
        '코드 클래스 구조는 C4 Code(VT-112) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-110', 'VT-112'],
    },
  },
  {
    id: 'VT-112',
    name: 'C4 Code',
    exportNames: ['C4CodeDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '코드 수준 요소 구조(≈클래스도)',
      dataShape: ['hierarchy', 'relationship'],
      primitives: ['node', 'edge'],
      aliases: [],
      useWhen: ['코드 수준 요소(클래스/인터페이스) 구조를 표현할 때'],
      avoidWhen: [
        '컴포넌트 책임 수준은 C4 Component(VT-111) 사용',
        '표준 UML 클래스는 Class(VT-101) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-101', 'VT-111'],
    },
  },
  {
    id: 'VT-113',
    name: 'C4 Dynamic',
    exportNames: ['C4DynamicDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: 'C4 요소 간 순서 있는 협력',
      dataShape: ['process', 'temporal'],
      primitives: ['node', 'edge'],
      aliases: [],
      useWhen: [
        'C4 요소 간 런타임 협력을 순번으로 표현할 때',
        '특정 유스케이스의 흐름을 설명할 때',
      ],
      avoidWhen: [
        '정적 구성은 C4 Container(VT-110)/Component(VT-111) 사용',
        '상세 메시지 명세는 Sequence(VT-108) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-108', 'VT-111'],
    },
  },
  {
    id: 'VT-114',
    name: 'C4 System Landscape',
    exportNames: ['C4SystemLandscapeDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '다중 시스템 전경도',
      dataShape: ['relationship', 'network'],
      primitives: ['node', 'edge', 'boundary'],
      aliases: [],
      useWhen: ['여러 시스템의 전사 전경을 지도로 표현할 때'],
      avoidWhen: ['단일 시스템 범위는 C4 Context(VT-109) 사용'],
      tags: ['diagram', 'standard'],
      related: ['VT-109'],
    },
  },
  {
    id: 'VT-115',
    name: 'Cloud Architecture Diagram',
    exportNames: ['ArchitectureDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '클라우드 서비스 구성도',
      dataShape: ['relationship', 'network'],
      primitives: ['node', 'edge', 'boundary'],
      aliases: ['AWS/Azure/GCP diagram', 'architecture-beta'],
      useWhen: [
        '클라우드 서비스 구성과 연결을 설계·소통할 때',
        '중립 아이콘으로 인프라를 도식할 때',
      ],
      avoidWhen: [
        '논리 UML 배치는 Deployment(VT-104) 사용',
        '네트워크 세그먼트 경계는 Network Topology(VT-125) 사용',
      ],
      tags: ['diagram'],
      related: ['VT-104', 'VT-125'],
    },
  },
  {
    id: 'VT-116',
    name: 'Block Diagram',
    exportNames: ['BlockDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '기능 블록과 연결 구조',
      dataShape: ['relationship'],
      primitives: ['node', 'edge', 'grid'],
      aliases: ['block-beta', 'functional block'],
      useWhen: ['기능 블록과 연결로 시스템을 분해할 때'],
      avoidWhen: ['표준 컴포넌트 배선은 Component(VT-103) 사용'],
      tags: ['diagram'],
      related: ['VT-103'],
    },
  },
  {
    id: 'VT-117',
    name: 'ER Diagram',
    exportNames: ['ERDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '엔터티·관계·카디널리티 모델',
      dataShape: ['relationship'],
      primitives: ['node', 'edge'],
      aliases: ['erDiagram', 'IE notation', 'ERD'],
      useWhen: ['DB 스키마의 엔터티·관계·카디널리티를 설계할 때'],
      avoidWhen: [
        '클래스 행위 포함 모델은 Class(VT-101) 사용',
        '데이터 흐름은 Data-Flow(VT-126) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-101'],
    },
  },
  {
    id: 'VT-118',
    name: 'Requirement Diagram',
    exportNames: ['RequirementDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '요구-검증-충족 관계 모델',
      dataShape: ['relationship'],
      primitives: ['node', 'edge'],
      aliases: ['requirementDiagram(SysML)'],
      useWhen: ['요구-검증-충족(satisfy/verify) 추적성을 모델링할 때'],
      avoidWhen: ['기능 범위 정의는 Use Case(VT-105) 사용'],
      tags: ['diagram', 'standard'],
      related: ['VT-105', 'VT-119'],
    },
  },
  {
    id: 'VT-119',
    name: 'SysML Block Definition',
    exportNames: ['SysMLBlockDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '«block» 정의·조성 구조',
      dataShape: ['hierarchy', 'relationship'],
      primitives: ['node', 'edge', 'tree'],
      aliases: ['BDD'],
      useWhen: ['시스템 블록의 정의와 조성(composition) 구조를 표현할 때'],
      avoidWhen: ['소프트웨어 클래스 모델은 Class(VT-101) 사용'],
      tags: ['diagram', 'standard'],
      related: ['VT-101', 'VT-118'],
    },
  },
  {
    id: 'VT-120',
    name: 'ArchiMate Layered View',
    // 다-export 유형: 통합 + 레이어별 3종.
    exportNames: [
      'ArchiMateDiagram',
      'ArchiMateBusinessDiagram',
      'ArchiMateApplicationDiagram',
      'ArchiMateTechnologyDiagram',
    ],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '비즈니스~기술 계층 통합 EA 뷰',
      dataShape: ['relationship', 'hierarchy'],
      primitives: ['node', 'edge', 'lane'],
      aliases: ['layered viewpoint'],
      useWhen: [
        '비즈니스·애플리케이션·기술 계층을 통합한 EA 뷰를 표현할 때',
        '레이어 밴드로 계층을 구분할 때',
      ],
      avoidWhen: ['동기·전략·이행 관점은 ArchiMate Viewpoints(VT-121) 사용'],
      tags: ['diagram', 'standard'],
      related: ['VT-121'],
    },
  },
  {
    id: 'VT-121',
    name: 'ArchiMate Extended Viewpoints',
    exportNames: ['ArchiMateViewpointDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '동기·전략·이행 관점 EA 뷰 묶음',
      dataShape: ['relationship', 'concept'],
      primitives: ['node', 'edge', 'boundary'],
      aliases: ['motivation', 'strategy/capability map', 'implementation & migration'],
      useWhen: ['동기·전략·이행 등 특정 관점의 EA 뷰가 필요할 때'],
      avoidWhen: ['계층 통합 뷰는 ArchiMate Layered(VT-120) 사용'],
      tags: ['diagram', 'standard'],
      related: ['VT-120'],
    },
  },
  {
    id: 'VT-122',
    name: 'BPMN Process Diagram',
    exportNames: ['BPMNDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '단일 참여자 업무 절차 모델',
      dataShape: ['process'],
      primitives: ['node', 'edge', 'lane'],
      aliases: ['orchestration', 'private process'],
      useWhen: ['단일 조직의 업무 절차를 표준 BPMN으로 모델링할 때'],
      avoidWhen: [
        '풀 간 메시지 교환은 BPMN Collaboration(VT-123) 사용',
        '비표준 범용 도식은 Flowchart(VT-201) 사용',
      ],
      tags: ['diagram', 'standard'],
      related: ['VT-123', 'VT-201'],
    },
  },
  {
    id: 'VT-123',
    name: 'BPMN Collaboration',
    exportNames: ['BPMNCollaborationDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '풀 간 메시지 교환 모델',
      dataShape: ['process', 'flow'],
      primitives: ['node', 'edge', 'lane'],
      aliases: ['choreography', 'conversation'],
      useWhen: ['여러 조직(풀) 간 메시지 교환 협업을 모델링할 때'],
      avoidWhen: ['단일 참여자 절차는 BPMN Process(VT-122) 사용'],
      tags: ['diagram', 'standard'],
      related: ['VT-122'],
    },
  },
  {
    id: 'VT-124',
    name: 'DMN Decision Requirements',
    exportNames: ['DMNDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '의사결정-입력-지식 요구 관계',
      dataShape: ['relationship'],
      primitives: ['node', 'edge'],
      aliases: ['DRD', 'DRG'],
      useWhen: ['비즈니스 룰의 의사결정-입력-지식 요구 관계를 모델링할 때'],
      avoidWhen: ['절차 흐름은 BPMN Process(VT-122) 사용'],
      tags: ['diagram', 'standard'],
      related: ['VT-122'],
    },
  },
  {
    id: 'VT-125',
    name: 'Network Topology',
    exportNames: ['NetworkTopology'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '네트워크 세그먼트·장비 토폴로지',
      dataShape: ['network'],
      primitives: ['node', 'edge', 'lane'],
      aliases: ['nwdiag', 'network diagram'],
      useWhen: [
        '네트워크 세그먼트와 장비 토폴로지를 표현할 때',
        '보안 존 경계를 구분할 때',
      ],
      avoidWhen: ['클라우드 서비스 구성은 Cloud Architecture(VT-115) 사용'],
      tags: ['diagram'],
      related: ['VT-115'],
    },
  },
  {
    id: 'VT-126',
    name: 'Data-Flow Diagram',
    exportNames: ['DataFlowDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '데이터 이동·변환·저장 흐름',
      dataShape: ['flow', 'process'],
      primitives: ['node', 'edge', 'boundary'],
      aliases: ['DFD', 'threat-model DFD'],
      useWhen: [
        '데이터의 이동·변환·저장 흐름을 표현할 때',
        '위협 모델 경계를 그릴 때',
      ],
      avoidWhen: [
        '정적 스키마 관계는 ER(VT-117) 사용',
        '데이터 계보 추적은 Data Lineage(VT-127) 사용',
      ],
      tags: ['diagram'],
      related: ['VT-127'],
    },
  },
  {
    id: 'VT-127',
    name: 'Data Lineage',
    exportNames: ['DataLineage'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '데이터 계보·파이프라인 추적',
      dataShape: ['flow', 'network'],
      primitives: ['node', 'edge'],
      aliases: ['lineage'],
      useWhen: ['데이터 계보와 파이프라인 경로를 추적할 때'],
      avoidWhen: ['위협 모델 데이터 흐름은 Data-Flow(VT-126) 사용'],
      tags: ['diagram'],
      related: ['VT-126'],
    },
  },
  {
    id: 'VT-128',
    name: 'Packet Diagram',
    exportNames: ['PacketDiagram'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '프로토콜 패킷 비트 필드 배치',
      dataShape: ['relationship'],
      primitives: ['grid', 'axis'],
      aliases: ['packet'],
      useWhen: ['프로토콜 패킷의 비트/바이트 필드 배치를 문서화할 때'],
      avoidWhen: ['연속 값 분포는 Histogram(VT-508) 사용'],
      tags: ['diagram', 'standard'],
    },
  },
  {
    id: 'VT-129',
    name: 'Git Graph',
    exportNames: ['GitGraph'],
    kind: 'template',
    meta: {
      category: 'engineering',
      summary: '브랜치·커밋·머지 이력',
      dataShape: ['temporal', 'network'],
      primitives: ['node', 'edge', 'lane', 'axis'],
      aliases: ['gitGraph'],
      useWhen: ['브랜치·커밋·머지 이력으로 Git 전략을 설명할 때'],
      avoidWhen: ['일반 시간축 사건은 Timeline(VT-401) 사용'],
      tags: ['diagram', 'time'],
      related: ['VT-401'],
    },
  },

  // ── B. 프로세스·플로우 (VT-2xx) ──────────────────────────────────────────────
  {
    id: 'VT-201',
    name: 'Flowchart',
    exportNames: ['Flowchart'],
    kind: 'template',
    meta: {
      category: 'process-flow',
      summary: '노드·간선 절차와 분기',
      dataShape: ['process'],
      primitives: ['node', 'edge'],
      aliases: ['graph', 'decision flowchart'],
      useWhen: [
        '분기가 있는 범용 절차를 도식할 때',
        '의사결정 흐름을 표현할 때',
      ],
      avoidWhen: [
        '표준 업무 절차는 BPMN(VT-122) 사용',
        '스윔레인 병행 절차는 Activity(VT-106) 사용',
        '분기 없는 선형 절차는 Process Steps(VT-202) 사용',
      ],
      tags: ['diagram'],
      related: ['VT-106', 'VT-202'],
    },
  },
  {
    id: 'VT-202',
    name: 'Process Steps',
    exportNames: ['ProcessSteps'],
    kind: 'pattern',
    meta: {
      category: 'process-flow',
      summary: '순차 스텝 체인(배지+커넥터)',
      dataShape: ['process'],
      primitives: ['node', 'leader', 'grid'],
      aliases: ['process infographic', 'how-to', 'step-by-step'],
      useWhen: [
        '튜토리얼/워크플로를 순서대로 안내할 때',
        '분기 없는 선형 절차를 강조할 때',
      ],
      avoidWhen: [
        '조건 분기가 있으면 Flowchart(VT-201) 사용',
        '끝이 처음으로 돌아오는 순환이면 Cycle(VT-203) 사용',
      ],
      tags: ['infographic'],
      related: ['VT-201', 'VT-208'],
    },
  },
  {
    id: 'VT-203',
    name: 'Cycle',
    exportNames: ['Cycle'],
    kind: 'pattern',
    meta: {
      category: 'process-flow',
      summary: '순환 폐쇄 링/오빗 프로세스',
      dataShape: ['process'],
      primitives: ['radial', 'edge'],
      aliases: ['cycle diagram', 'loop'],
      useWhen: [
        '끝이 처음으로 돌아오는 반복 프로세스일 때',
        '단계가 순환 관계일 때',
      ],
      avoidWhen: [
        '선형 절차는 Process Steps(VT-202) 사용',
        '가속 선순환 강조는 flywheel variant(VT-708) 사용',
        '장기 phase 나선은 spiral variant(VT-405) 사용',
      ],
      tags: ['infographic', 'radial'],
      related: ['VT-405', 'VT-708'],
    },
  },
  {
    id: 'VT-204',
    name: 'Kanban Board',
    exportNames: ['KanbanBoard'],
    kind: 'template',
    meta: {
      category: 'process-flow',
      summary: '상태 컬럼별 카드 보드',
      dataShape: ['process'],
      primitives: ['lane', 'node'],
      aliases: ['kanban'],
      useWhen: ['상태 컬럼(To Do/Doing/Done)으로 작업 흐름을 관리할 때'],
      avoidWhen: ['시간 기반 일정은 Gantt(VT-403) 사용'],
      tags: ['diagram'],
      related: ['VT-403'],
    },
  },
  {
    id: 'VT-205',
    name: 'User Journey Map',
    exportNames: ['UserJourneyMap'],
    kind: 'template',
    meta: {
      category: 'process-flow',
      summary: '여정 단계+만족도/감정 곡선',
      dataShape: ['process', 'temporal'],
      primitives: ['lane', 'axis', 'node'],
      aliases: ['journey', 'customer journey map'],
      useWhen: [
        '사용자 여정 단계별 감정/만족도를 표현할 때',
        'UX 리서치 결과를 소통할 때',
      ],
      avoidWhen: [
        '날짜 기반 여정 일정은 User Journey Gantt(VT-404) 사용',
        '화면 이동 흐름은 Screen Flow(VT-206) 사용',
      ],
      tags: ['diagram'],
      related: ['VT-404'],
    },
  },
  {
    id: 'VT-206',
    name: 'Screen Flow',
    exportNames: ['ScreenFlow'],
    kind: 'template',
    meta: {
      category: 'process-flow',
      summary: '화면 목업 노드 간 이동 흐름',
      dataShape: ['process', 'network'],
      primitives: ['node', 'edge', 'mockup'],
      aliases: ['wireflow', 'user-flow'],
      useWhen: ['화면 목업 간 이동 흐름을 설계·소통할 때'],
      avoidWhen: [
        '감정 곡선 여정은 User Journey Map(VT-205) 사용',
        '추상 절차는 Flowchart(VT-201) 사용',
      ],
      tags: ['diagram'],
      related: ['VT-205', 'VT-201'],
    },
  },
  {
    id: 'VT-207',
    name: 'Funnel',
    exportNames: ['Funnel'],
    kind: 'pattern',
    meta: {
      category: 'process-flow',
      summary: '단계 축소형 전환 구조',
      dataShape: ['process', 'magnitude'],
      primitives: ['area'],
      aliases: ['sales funnel', 'marketing funnel', 'AIDA'],
      useWhen: ['단계별 전환/이탈을 축소형 구조로 표현할 때'],
      avoidWhen: ['층상 중요도 계층은 Pyramid(VT-701) 사용'],
      tags: ['infographic'],
      related: ['VT-701'],
    },
  },
  {
    id: 'VT-208',
    name: 'Pathways',
    exportNames: ['Pathways'],
    kind: 'pattern',
    meta: {
      category: 'process-flow',
      summary: '경로/노선 위 이정표 배열',
      dataShape: ['process'],
      primitives: ['edge', 'node', 'leader'],
      aliases: ['route infographic', 'tube-map style route'],
      useWhen: ['커리큘럼/여정 경로 위 이정표를 배열할 때'],
      avoidWhen: ['분기 절차는 Flowchart(VT-201) 사용'],
      tags: ['infographic'],
      related: ['VT-202'],
    },
  },

  // ── C. 계층·관계 (VT-3xx) ────────────────────────────────────────────────────
  {
    id: 'VT-301',
    name: 'Mindmap',
    exportNames: ['Mindmap'],
    kind: 'template',
    meta: {
      category: 'hierarchy-relation',
      summary: '중심 주제 방사형 위계 확장',
      dataShape: ['hierarchy'],
      primitives: ['radial', 'tree', 'edge'],
      aliases: ['mind map', 'Buzan map', 'radial map'],
      useWhen: [
        '중심 주제에서 방사형으로 아이디어를 확장할 때',
        '브레인스토밍 구조를 잡을 때',
      ],
      avoidWhen: ['라벨 붙은 개념 관계망은 Concept Map(VT-302) 사용'],
      tags: ['diagram', 'radial'],
      related: ['VT-302'],
    },
  },
  {
    id: 'VT-302',
    name: 'Concept Map',
    exportNames: ['ConceptMap'],
    kind: 'template',
    meta: {
      category: 'hierarchy-relation',
      summary: '라벨 붙은 연결선의 개념 관계망',
      dataShape: ['network', 'concept'],
      primitives: ['node', 'edge'],
      aliases: ['Novak map', 'knowledge map'],
      useWhen: ['개념 간 관계를 라벨 붙은 연결선으로 구조화할 때'],
      avoidWhen: ['단일 중심 방사 위계는 Mindmap(VT-301) 사용'],
      tags: ['diagram'],
      related: ['VT-301'],
    },
  },
  {
    id: 'VT-303',
    name: 'Hierarchy / Tree',
    exportNames: ['Hierarchy'],
    kind: 'pattern',
    meta: {
      category: 'hierarchy-relation',
      summary: '루트-자식 재귀 트리',
      dataShape: ['hierarchy'],
      primitives: ['tree', 'node', 'edge'],
      aliases: ['org chart', 'tree diagram', 'hierarchical infographic'],
      useWhen: ['조직/분류의 루트-자식 재귀 구조를 표현할 때'],
      avoidWhen: [
        '층상 비율 계층은 Pyramid(VT-701) 사용',
        '작업 분해는 WBS(VT-307) 사용',
      ],
      tags: ['diagram'],
      related: ['VT-701', 'VT-307'],
    },
  },
  {
    id: 'VT-304',
    name: 'Sitemap Tree',
    exportNames: ['SitemapTree'],
    kind: 'template',
    meta: {
      category: 'hierarchy-relation',
      summary: '사이트 IA 전용 트리(elbow)',
      dataShape: ['hierarchy'],
      primitives: ['tree', 'edge'],
      aliases: ['IA tree', 'sitemap'],
      useWhen: ['사이트 정보구조(IA)를 elbow 트리로 설계할 때'],
      avoidWhen: ['일반 조직 트리는 Hierarchy(VT-303) 사용'],
      tags: ['diagram'],
      related: ['VT-303'],
    },
  },
  {
    id: 'VT-305',
    name: 'Network Graph',
    exportNames: ['NetworkGraph'],
    kind: 'template',
    meta: {
      category: 'hierarchy-relation',
      summary: '노드·엣지 관계망(비계층)',
      dataShape: ['network'],
      primitives: ['node', 'edge', 'radial'],
      aliases: ['node-link', 'force graph', 'semantic network'],
      useWhen: [
        '비계층 노드·엣지 관계망을 분석할 때',
        '허브 노드를 강조할 때',
      ],
      avoidWhen: [
        '계층 트리는 Hierarchy(VT-303) 사용',
        '라벨 개념 관계는 Concept Map(VT-302) 사용',
      ],
      tags: ['diagram'],
      related: ['VT-302', 'VT-303'],
    },
  },
  {
    id: 'VT-306',
    name: 'Venn Diagram',
    exportNames: ['Venn'],
    kind: 'pattern',
    meta: {
      category: 'hierarchy-relation',
      summary: '집합 겹침 원 교차',
      dataShape: ['comparison', 'part-to-whole'],
      primitives: ['area'],
      aliases: ['Euler diagram', 'set diagram'],
      useWhen: [
        '집합 간 교집합·공통 요소를 표현할 때',
        '2~3개 개념의 겹침을 비교할 때',
      ],
      avoidWhen: ['정량 비율은 Pie(VT-506) 사용'],
      tags: ['chart', 'framework'],
      related: ['VT-506'],
    },
  },
  {
    id: 'VT-307',
    name: 'Work Breakdown Structure',
    exportNames: ['WorkBreakdownStructure'],
    kind: 'template',
    meta: {
      category: 'hierarchy-relation',
      summary: '산출물 중심 작업 분해 트리',
      dataShape: ['hierarchy'],
      primitives: ['tree', 'node'],
      aliases: ['WBS'],
      useWhen: [
        '프로젝트 산출물을 계층적으로 분해할 때',
        '범위를 작업 단위로 나눌 때',
      ],
      avoidWhen: [
        '일정은 Gantt(VT-403) 사용',
        '일반 조직 트리는 Hierarchy(VT-303) 사용',
      ],
      tags: ['diagram'],
      related: ['VT-303', 'VT-403'],
    },
  },

  // ── D. 시간축 (VT-4xx) ───────────────────────────────────────────────────────
  {
    id: 'VT-401',
    name: 'Timeline',
    exportNames: ['TimelineDiagram'],
    kind: 'template',
    meta: {
      category: 'time',
      summary: '사건의 시간순 나열',
      dataShape: ['temporal', 'change-over-time'],
      primitives: ['axis', 'node'],
      aliases: ['chronology', 'timeline infographic'],
      useWhen: [
        '사건을 시간순으로 나열할 때',
        '연혁/전개를 표현할 때',
      ],
      avoidWhen: [
        '기간 막대 일정은 Gantt(VT-403) 사용',
        '마일스톤 로드맵은 Timeline Roadmap(VT-402) 사용',
      ],
      tags: ['time', 'infographic'],
      related: ['VT-402', 'VT-403'],
    },
  },
  {
    id: 'VT-402',
    name: 'Timeline Roadmap',
    exportNames: ['TimelineRoadmap'],
    kind: 'pattern',
    meta: {
      category: 'time',
      summary: '마일스톤·기간 로드맵(chevron)',
      dataShape: ['temporal'],
      primitives: ['axis', 'node'],
      aliases: ['product roadmap', 'milestones'],
      useWhen: ['마일스톤과 기간을 로드맵으로 공유할 때'],
      avoidWhen: [
        '상세 작업 일정은 Gantt(VT-403) 사용',
        '사건 나열은 Timeline(VT-401) 사용',
      ],
      tags: ['time', 'infographic'],
      related: ['VT-401', 'VT-403'],
    },
  },
  {
    id: 'VT-403',
    name: 'Gantt Chart',
    exportNames: ['GanttChart'],
    kind: 'template',
    meta: {
      category: 'time',
      summary: '작업·기간 시간축 막대 일정',
      dataShape: ['temporal'],
      primitives: ['axis', 'band', 'lane'],
      aliases: ['gantt', 'project schedule'],
      useWhen: ['작업과 기간을 시간축 막대로 일정 관리할 때'],
      avoidWhen: [
        '마일스톤 요약은 Timeline Roadmap(VT-402) 사용',
        '상태 보드는 Kanban(VT-204) 사용',
      ],
      tags: ['chart', 'time'],
      related: ['VT-402', 'VT-404'],
    },
  },
  {
    id: 'VT-404',
    name: 'User Journey Gantt',
    exportNames: ['UserJourneyGantt'],
    kind: 'template',
    meta: {
      category: 'time',
      summary: '여정 pill과 날짜축 결합',
      dataShape: ['temporal'],
      primitives: ['axis', 'band', 'node'],
      aliases: ['journey gantt'],
      useWhen: ['여정 단계를 날짜축과 결합해 일정화할 때'],
      avoidWhen: ['감정 곡선 여정은 User Journey Map(VT-205) 사용'],
      tags: ['chart', 'time'],
      related: ['VT-205', 'VT-403'],
    },
  },
  {
    id: 'VT-405',
    name: 'Radial / Spiral Phase',
    exportNames: ['Cycle'],
    kind: 'pattern',
    variant: 'spiral',
    meta: {
      category: 'time',
      summary: '나선/원주 위 단계 배열',
      dataShape: ['process', 'temporal'],
      primitives: ['radial', 'axis'],
      aliases: ['spiral phase', 'circular phase'],
      useWhen: [
        '장기 phase를 나선/원주 위에 배열할 때',
        'spiral variant로 렌더할 때',
      ],
      avoidWhen: ['단순 순환 링은 Cycle(VT-203) 사용'],
      tags: ['radial', 'time'],
      related: ['VT-203'],
    },
  },

  // ── E. 데이터 차트 (VT-5xx) ──────────────────────────────────────────────────
  {
    id: 'VT-501',
    name: 'Bar Chart',
    exportNames: ['BarChart'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '범주 값의 막대 길이로 크기를 비교',
      dataShape: ['magnitude', 'ranking'],
      primitives: ['axis', 'band'],
      aliases: ['column', 'grouped bar', 'paired bar'],
      useWhen: [
        '범주 간 수치 크기를 직접 비교할 때',
        '순위를 막대 길이로 드러낼 때',
        '항목 수가 과다하지 않을 때',
      ],
      avoidWhen: [
        '부분-전체 구성비가 핵심이면 Pie(VT-506)/Stacked Bar(VT-502) 사용',
        '시간 연속 추세는 Line(VT-503) 사용',
        '두 변수 상관은 Scatter(VT-505) 사용',
      ],
      tags: ['chart'],
      related: ['VT-502', 'VT-509'],
    },
  },
  {
    id: 'VT-502',
    name: 'Stacked Bar',
    exportNames: ['StackedBarChart'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '막대 분할로 합+구성 동시 표시',
      dataShape: ['part-to-whole', 'deviation'],
      primitives: ['axis', 'band'],
      aliases: ['proportional stacked', 'diverging', 'spine'],
      useWhen: [
        '합계와 구성비를 한 막대에서 동시에 볼 때',
        '발산형(diverging)으로 기준 대비를 표현할 때',
      ],
      avoidWhen: [
        '단순 크기 비교는 Bar(VT-501) 사용',
        '전체 대비 비율만이면 Pie(VT-506) 사용',
      ],
      tags: ['chart'],
      related: ['VT-501', 'VT-506'],
    },
  },
  {
    id: 'VT-503',
    name: 'Line Chart',
    exportNames: ['LineChart'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '시간축 값 변화 선 연결',
      dataShape: ['change-over-time'],
      primitives: ['axis', 'edge'],
      aliases: ['line', 'multiple lines'],
      useWhen: [
        '연속 시간에 따른 추세를 볼 때',
        '여러 계열 추세를 비교할 때',
      ],
      avoidWhen: [
        '범주 크기 비교는 Bar(VT-501) 사용',
        '총량 강조는 Area(VT-504) 사용',
      ],
      tags: ['chart'],
      related: ['VT-504', 'VT-501'],
    },
  },
  {
    id: 'VT-504',
    name: 'Area Chart',
    exportNames: ['AreaChart'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '선 아래 채움으로 총량 강조',
      dataShape: ['change-over-time', 'part-to-whole'],
      primitives: ['axis', 'area'],
      aliases: ['stacked area'],
      useWhen: [
        '시간에 따른 총량 변화를 강조할 때',
        '누적 구성 추세를 볼 때',
      ],
      avoidWhen: ['개별 계열 값 비교는 Line(VT-503) 사용'],
      tags: ['chart'],
      related: ['VT-503'],
    },
  },
  {
    id: 'VT-505',
    name: 'Scatterplot',
    exportNames: ['ScatterPlot'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '두 변수 관계 점 표시',
      dataShape: ['correlation', 'distribution'],
      primitives: ['axis', 'node'],
      aliases: ['XY plot', 'bubble', 'connected scatter'],
      useWhen: [
        '두 연속 변수의 상관을 볼 때',
        '버블로 3번째 변수를 크기 인코딩할 때',
      ],
      avoidWhen: [
        '범주 비교는 Bar(VT-501) 사용',
        '단변량 분포는 Histogram(VT-508) 사용',
      ],
      tags: ['chart'],
      related: ['VT-508'],
    },
  },
  {
    id: 'VT-506',
    name: 'Pie / Donut',
    exportNames: ['PieChart'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '부채꼴 구성비',
      dataShape: ['part-to-whole'],
      primitives: ['radial', 'area'],
      aliases: ['donut', 'arc', 'multiple pies'],
      useWhen: ['전체 대비 소수 범주의 구성비를 볼 때'],
      avoidWhen: [
        '범주가 많거나 정밀 비교가 필요하면 Bar(VT-501) 사용',
        '합+구성 동시 표현은 Stacked Bar(VT-502) 사용',
      ],
      tags: ['chart', 'radial'],
      related: ['VT-501', 'VT-502'],
    },
  },
  {
    id: 'VT-507',
    name: 'Treemap',
    exportNames: ['Treemap'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '중첩 사각형 면적 계층·비중',
      dataShape: ['part-to-whole', 'hierarchy'],
      primitives: ['grid', 'area', 'tree'],
      aliases: [],
      useWhen: [
        '계층 데이터의 비중을 면적으로 표현할 때',
        '많은 범주의 부분-전체를 압축해서 볼 때',
      ],
      avoidWhen: [
        '단순 비율은 Pie(VT-506) 사용',
        '순수 계층 구조는 Hierarchy(VT-303) 사용',
      ],
      tags: ['chart'],
      related: ['VT-506', 'VT-303'],
    },
  },
  {
    id: 'VT-508',
    name: 'Histogram',
    exportNames: ['Histogram'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '구간 빈도 연속 막대',
      dataShape: ['distribution'],
      primitives: ['axis', 'band'],
      aliases: [],
      useWhen: ['연속 변수의 구간별 빈도 분포를 볼 때'],
      avoidWhen: [
        '범주 비교는 Bar(VT-501) 사용',
        '사분위 요약은 Boxplot(VT-510) 사용',
      ],
      tags: ['chart'],
      related: ['VT-510', 'VT-501'],
    },
  },
  {
    id: 'VT-509',
    name: 'Dot Plot',
    exportNames: ['DotPlot'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '점 1~2개로 값·범위·변화 표시',
      dataShape: ['distribution', 'magnitude', 'ranking'],
      primitives: ['axis', 'node'],
      aliases: ['range plot', 'arrow plot', 'dumbbell'],
      useWhen: [
        '점으로 값을 표시하거나 dumbbell로 두 값 차이를 볼 때',
        '범위(range)를 표현할 때',
      ],
      avoidWhen: ['막대 길이 비교는 Bar(VT-501) 사용'],
      tags: ['chart'],
      related: ['VT-501'],
    },
  },
  {
    id: 'VT-510',
    name: 'Boxplot',
    exportNames: ['Boxplot'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '중앙값·사분위 상자 요약',
      dataShape: ['distribution'],
      primitives: ['axis', 'band', 'area'],
      aliases: ['box-and-whisker', 'Tukey'],
      useWhen: [
        '중앙값·사분위·이상치로 분포를 요약할 때',
        '여러 그룹 분포를 비교할 때',
      ],
      avoidWhen: ['원자료 빈도 형태는 Histogram(VT-508) 사용'],
      tags: ['chart'],
      related: ['VT-508'],
    },
  },
  {
    id: 'VT-511',
    name: 'Radar Chart',
    exportNames: ['RadarChart'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '방사 다축 다각형',
      dataShape: ['magnitude', 'comparison'],
      primitives: ['radial', 'axis', 'area'],
      aliases: ['spider', 'cobweb'],
      useWhen: ['여러 축의 값을 다각형으로 한눈에 비교할 때'],
      avoidWhen: ['축이 많거나 정밀 비교가 필요하면 Bar(VT-501) 사용'],
      tags: ['chart', 'radial'],
      related: ['VT-501'],
    },
  },
  {
    id: 'VT-512',
    name: 'Heatmap',
    exportNames: ['Heatmap'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '격자 색 농도 패턴',
      dataShape: ['correlation', 'magnitude'],
      primitives: ['grid', 'area'],
      aliases: ['calendar heatmap', 'XY heatmap'],
      useWhen: [
        '격자 위 값의 강도를 색 농도로 표현할 때',
        '달력/행렬 패턴을 볼 때',
      ],
      avoidWhen: ['정확한 값 비교는 Bar(VT-501) 사용'],
      tags: ['chart', 'matrix'],
      related: ['VT-501'],
    },
  },
  {
    id: 'VT-513',
    name: 'Waffle',
    exportNames: ['Statistics'],
    kind: 'pattern',
    variant: 'waffle',
    meta: {
      category: 'data-chart',
      summary: '단위 격자 채움 백분율',
      dataShape: ['part-to-whole'],
      primitives: ['grid', 'icon-unit'],
      aliases: ['gridplot', 'unit chart'],
      useWhen: [
        '백분율을 100셀 격자 채움으로 표현할 때',
        'waffle variant로 렌더할 때',
      ],
      avoidWhen: [
        '아이콘 반복 수량은 Isotype(VT-514) 사용',
        '부채꼴 비율은 Pie(VT-506) 사용',
      ],
      tags: ['chart', 'infographic'],
      related: ['VT-514', 'VT-506'],
    },
  },
  {
    id: 'VT-514',
    name: 'Isotype',
    exportNames: ['Statistics'],
    kind: 'pattern',
    variant: 'isotype',
    meta: {
      category: 'data-chart',
      summary: '아이콘 반복 수량(정수)',
      dataShape: ['magnitude', 'part-to-whole'],
      primitives: ['icon-unit', 'grid'],
      aliases: ['pictogram'],
      useWhen: [
        '아이콘을 반복해 정수 수량을 직관적으로 표현할 때',
        'isotype variant로 렌더할 때',
      ],
      avoidWhen: ['연속 비율은 Waffle(VT-513) 사용'],
      tags: ['chart', 'infographic'],
      related: ['VT-513'],
    },
  },
  {
    id: 'VT-515',
    name: 'Sankey',
    exportNames: ['SankeyDiagram'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '흐름 폭으로 이동량 표시',
      dataShape: ['flow'],
      primitives: ['band', 'edge'],
      aliases: ['alluvial', 'river plot'],
      useWhen: [
        '노드 간 이동량을 흐름 폭으로 표현할 때',
        '단계 간 배분을 볼 때',
      ],
      avoidWhen: ['원 둘레 간 상호 흐름은 Chord(VT-516) 사용'],
      tags: ['chart'],
      related: ['VT-516', 'VT-517'],
    },
  },
  {
    id: 'VT-516',
    name: 'Chord Diagram',
    exportNames: ['ChordDiagram'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '원 둘레 간 흐름 리본',
      dataShape: ['flow', 'network'],
      primitives: ['radial', 'band'],
      aliases: [],
      useWhen: ['개체 간 상호 흐름/연결을 원형 리본으로 표현할 때'],
      avoidWhen: ['방향성 단계 흐름은 Sankey(VT-515) 사용'],
      tags: ['chart', 'radial'],
      related: ['VT-515'],
    },
  },
  {
    id: 'VT-517',
    name: 'Waterfall',
    exportNames: ['WaterfallChart'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '증감 누적 단계 합계 도달',
      dataShape: ['flow', 'part-to-whole'],
      primitives: ['axis', 'band'],
      aliases: [],
      useWhen: ['증감을 누적해 최종 합계 도달 과정을 볼 때'],
      avoidWhen: [
        '이동량 흐름은 Sankey(VT-515) 사용',
        '단순 구성비는 Stacked Bar(VT-502) 사용',
      ],
      tags: ['chart'],
      related: ['VT-515', 'VT-502'],
    },
  },
  {
    id: 'VT-518',
    name: 'Choropleth Map',
    exportNames: ['ChoroplethMap'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '행정구역 색상 비율 지도',
      dataShape: ['spatial', 'magnitude'],
      primitives: ['geo', 'area'],
      aliases: [],
      useWhen: ['행정구역별 값을 색상 농도로 지도에 표현할 때'],
      avoidWhen: ['지도 위 마커 배치는 Geo Infographic(VT-605) 사용'],
      tags: ['chart', 'geo'],
      related: ['VT-605'],
    },
  },
  {
    id: 'VT-519',
    name: 'Radial Gauge',
    exportNames: ['RadialGauge'],
    kind: 'template',
    meta: {
      category: 'data-chart',
      summary: '아크 척도 위 값 표시',
      dataShape: ['magnitude'],
      primitives: ['radial', 'axis'],
      aliases: ['gauge', 'dial'],
      useWhen: ['단일 KPI를 아크 척도 위 값으로 표시할 때'],
      avoidWhen: ['여러 범주 비교는 Bar(VT-501) 사용'],
      tags: ['chart', 'radial'],
      related: ['VT-501'],
    },
  },
  // VT-520 Data Table — ⛔ 범위외(DOM 테이블 영역), 제외.

  // ── F. 인포그래픽/에디토리얼 (VT-6xx) ────────────────────────────────────────
  {
    id: 'VT-601',
    name: 'Statistical Infographic',
    exportNames: ['Statistics'],
    kind: 'pattern',
    variant: 'cards',
    meta: {
      category: 'infographic-editorial',
      summary: '수치 강조 카드/그리드 구성',
      dataShape: ['magnitude', 'comparison'],
      primitives: ['grid', 'node'],
      aliases: ['data infographic', 'stat cards'],
      useWhen: [
        '핵심 수치를 카드/그리드로 강조할 때',
        '성과·리서치를 요약할 때',
        'cards variant로 렌더할 때',
      ],
      avoidWhen: [
        '정밀 추세는 Line(VT-503) 사용',
        '아이콘 반복 수량은 Isotype(VT-514) 사용',
      ],
      tags: ['infographic'],
      related: ['VT-514', 'VT-513'],
    },
  },
  {
    id: 'VT-602',
    name: 'Comparison',
    exportNames: ['Comparison'],
    kind: 'pattern',
    meta: {
      category: 'infographic-editorial',
      summary: '패널 대비+중앙 디바이더',
      dataShape: ['comparison'],
      primitives: ['grid', 'area'],
      aliases: ['versus', 'before-after', 'T-chart'],
      useWhen: [
        '두 대상을 패널로 나란히 대비할 때',
        'before-after/pros-cons를 표현할 때',
      ],
      avoidWhen: [
        '전략 4분면은 SWOT(VT-703) 사용',
        '정량 2축 배치는 Quadrant(VT-702) 사용',
      ],
      tags: ['infographic'],
      related: ['VT-703', 'VT-702'],
    },
  },
  {
    id: 'VT-603',
    name: 'List Infographic',
    exportNames: ['ListInfographic'],
    kind: 'pattern',
    meta: {
      category: 'infographic-editorial',
      summary: '아이콘+항목 목록 시각화',
      dataShape: ['concept'],
      primitives: ['grid', 'icon-unit', 'leader'],
      aliases: ['listicle', 'checklist'],
      useWhen: ['팁/체크리스트를 아이콘+항목 행으로 시각화할 때'],
      avoidWhen: ['텍스트 중심 개요는 Informational(VT-604) 사용'],
      tags: ['infographic'],
      related: ['VT-604'],
    },
  },
  {
    id: 'VT-604',
    name: 'Informational Infographic',
    exportNames: ['InformationalInfographic'],
    kind: 'pattern',
    meta: {
      category: 'infographic-editorial',
      summary: '텍스트 중심 개요 구성',
      dataShape: ['concept'],
      primitives: ['grid', 'leader'],
      aliases: ['descriptive'],
      useWhen: [
        '텍스트 중심으로 개념을 소개할 때',
        '헤딩+인트로+섹션 그리드로 개요를 구성할 때',
      ],
      avoidWhen: ['목록형은 List Infographic(VT-603) 사용'],
      tags: ['infographic'],
      related: ['VT-603'],
    },
  },
  {
    id: 'VT-605',
    name: 'Geo / Map Infographic',
    exportNames: ['GeoMap'],
    kind: 'pattern',
    meta: {
      category: 'infographic-editorial',
      summary: '지도 위 데이터·마커 배치',
      dataShape: ['spatial'],
      primitives: ['geo', 'node', 'leader'],
      aliases: ['geographic', 'location infographic'],
      useWhen: ['지도 위에 마커/데이터를 배치해 지역 트렌드를 표현할 때'],
      avoidWhen: ['행정구역 색상 비율은 Choropleth(VT-518) 사용'],
      tags: ['infographic', 'geo'],
      related: ['VT-518'],
    },
  },
  {
    id: 'VT-606',
    name: 'Annotated Illustration',
    exportNames: ['AnnotatedIllustration'],
    kind: 'pattern',
    meta: {
      category: 'infographic-editorial',
      summary: '대상 구조 라벨링 해설',
      dataShape: ['concept'],
      primitives: ['leader', 'node'],
      aliases: ['anatomical', 'labeled diagram', 'cutaway'],
      useWhen: [
        '대상 구조를 라벨(콜아웃)로 해설할 때',
        '제품/구조를 설명할 때',
      ],
      avoidWhen: ['지도 위 마커는 Geo Infographic(VT-605) 사용'],
      tags: ['infographic'],
      related: ['VT-605'],
    },
  },
  {
    id: 'VT-607',
    name: 'Bento Grid',
    exportNames: ['BentoGrid'],
    kind: 'pattern',
    meta: {
      category: 'infographic-editorial',
      summary: '비대칭 모듈 격자 배치',
      dataShape: ['concept'],
      primitives: ['grid', 'area'],
      aliases: ['bento layout', 'collage grid'],
      useWhen: ['비대칭 모듈 격자로 피처/대시보드를 배치할 때'],
      avoidWhen: ['정형 통계 카드는 Statistical Infographic(VT-601) 사용'],
      tags: ['infographic'],
      related: ['VT-601'],
    },
  },
  {
    id: 'VT-608',
    name: 'Sketchnote Composition',
    exportNames: ['Sketchnote'],
    kind: 'pattern',
    meta: {
      category: 'infographic-editorial',
      summary: '손그림·화살표 시각 노트 구성',
      dataShape: ['concept'],
      primitives: ['node', 'edge', 'leader'],
      aliases: ['visual note'],
      useWhen: ['강연/아이디어를 손그림·화살표 노트로 기록할 때'],
      avoidWhen: ['정형 개념 관계는 Concept Map(VT-302) 사용'],
      tags: ['infographic'],
      related: ['VT-302'],
    },
  },
  {
    id: 'VT-609',
    name: 'Poster / Editorial Title',
    exportNames: ['PosterEditorial'],
    kind: 'pattern',
    meta: {
      category: 'infographic-editorial',
      summary: '타이포 위계 중심 지면 구성',
      dataShape: ['concept'],
      primitives: ['grid', 'area'],
      aliases: ['magazine layout', 'editorial composition'],
      useWhen: ['타이포 위계 중심의 표지/타이틀 지면을 구성할 때'],
      avoidWhen: ['모듈 격자 배치는 Bento Grid(VT-607) 사용'],
      tags: ['editorial'],
      related: ['VT-607'],
    },
  },
  // VT-610 Infographic Resume · VT-611 Scrollytelling — ⛔ 범위외, 제외.

  // ── G. 개념 프레임워크 (VT-7xx) ──────────────────────────────────────────────
  {
    id: 'VT-701',
    name: 'Pyramid',
    exportNames: ['Hierarchy'],
    kind: 'pattern',
    variant: 'pyramid',
    meta: {
      category: 'concept-framework',
      summary: '기반→정점 층상 구조',
      dataShape: ['hierarchy', 'part-to-whole'],
      primitives: ['area'],
      aliases: ['layered pyramid', 'Maslow'],
      useWhen: [
        '기반→정점 층상 중요도/단계를 표현할 때',
        'pyramid variant로 렌더할 때',
      ],
      avoidWhen: [
        '전환 축소 구조는 Funnel(VT-207) 사용',
        '재귀 트리는 Hierarchy(VT-303) 사용',
      ],
      tags: ['framework'],
      related: ['VT-207', 'VT-303'],
    },
  },
  {
    id: 'VT-702',
    name: 'Quadrant / 2x2 Matrix',
    exportNames: ['QuadrantChart'],
    kind: 'template',
    meta: {
      category: 'concept-framework',
      summary: '두 축 4분면 배치',
      dataShape: ['comparison', 'correlation'],
      primitives: ['axis', 'grid', 'node'],
      aliases: ['quadrantChart', 'Eisenhower', 'BCG', 'prioritization matrix'],
      useWhen: [
        '두 정량/정성 축으로 항목을 4분면에 배치할 때',
        '우선순위/포트폴리오를 분류할 때',
      ],
      avoidWhen: ['정성 전략 진단은 SWOT(VT-703) 사용'],
      tags: ['chart', 'matrix'],
      related: ['VT-703'],
    },
  },
  {
    id: 'VT-703',
    name: 'SWOT Matrix',
    exportNames: ['SwotMatrix'],
    kind: 'pattern',
    meta: {
      category: 'concept-framework',
      summary: '강점·약점·기회·위협 4분면',
      dataShape: ['comparison', 'concept'],
      primitives: ['grid', 'area'],
      aliases: ['TOWS'],
      useWhen: [
        '전략 진단을 4분면으로 정리할 때',
        '내부/외부 × 긍정/부정 축으로 분류할 때',
      ],
      avoidWhen: [
        '정량 2축 배치는 Quadrant(VT-702) 사용',
        '단순 항목 대비는 Comparison(VT-602) 사용',
      ],
      tags: ['framework', 'matrix'],
      related: ['VT-702'],
    },
  },
  {
    id: 'VT-704',
    name: 'Iceberg',
    exportNames: ['Iceberg'],
    kind: 'pattern',
    meta: {
      category: 'concept-framework',
      summary: '수면 아래 숨은 구조 은유',
      dataShape: ['concept', 'hierarchy'],
      primitives: ['area', 'leader'],
      aliases: ['iceberg model'],
      useWhen: ['표면 현상과 그 아래 숨은 근본 원인을 은유로 표현할 때'],
      avoidWhen: ['동심원 근접 계층은 Onion(VT-705) 사용'],
      tags: ['framework'],
      related: ['VT-705'],
    },
  },
  {
    id: 'VT-705',
    name: 'Onion / Concentric',
    exportNames: ['OnionDiagram'],
    kind: 'pattern',
    meta: {
      category: 'concept-framework',
      summary: '동심원 근접도 레이어',
      dataShape: ['hierarchy', 'concept'],
      primitives: ['radial', 'area'],
      aliases: ['stakeholder onion', 'concentric layers'],
      useWhen: ['동심원 근접도로 이해관계자/의존 계층을 표현할 때'],
      avoidWhen: [
        '수직 층상 은유는 Iceberg(VT-704) 사용',
        '방사 위계는 Mindmap(VT-301) 사용',
      ],
      tags: ['framework', 'radial'],
      related: ['VT-704'],
    },
  },
  {
    id: 'VT-706',
    name: 'Fishbone',
    exportNames: ['Fishbone'],
    kind: 'template',
    meta: {
      category: 'concept-framework',
      summary: '생선뼈 원인 범주화',
      dataShape: ['concept', 'hierarchy'],
      primitives: ['edge', 'node'],
      aliases: ['Ishikawa', 'cause-and-effect'],
      useWhen: [
        '문제의 원인을 범주별 생선뼈로 분석할 때',
        '근본 원인 분석(RCA)을 할 때',
      ],
      avoidWhen: ['숨은 구조 은유는 Iceberg(VT-704) 사용'],
      tags: ['framework'],
      related: ['VT-704'],
    },
  },
  {
    id: 'VT-707',
    name: 'Business Model Canvas',
    exportNames: ['BusinessModelCanvas'],
    kind: 'pattern',
    meta: {
      category: 'concept-framework',
      summary: '9블록 사업 모델 한 장 정리',
      dataShape: ['concept', 'comparison'],
      primitives: ['grid', 'area'],
      aliases: ['BMC', 'lean canvas'],
      useWhen: ['사업 모델을 표준 9블록으로 한 장에 정리할 때'],
      avoidWhen: ['전략 진단 4분면은 SWOT(VT-703) 사용'],
      tags: ['framework'],
      related: ['VT-703'],
    },
  },
  {
    id: 'VT-708',
    name: 'Flywheel',
    exportNames: ['Cycle'],
    kind: 'pattern',
    variant: 'flywheel',
    meta: {
      category: 'concept-framework',
      summary: '축적 가속 선순환 바퀴',
      dataShape: ['process'],
      primitives: ['radial', 'edge'],
      aliases: ['virtuous cycle', 'momentum loop'],
      useWhen: [
        '축적으로 가속되는 성장 선순환을 설명할 때',
        'flywheel variant로 렌더할 때',
      ],
      avoidWhen: ['단순 반복 순환은 Cycle(VT-203) 사용'],
      tags: ['framework', 'radial'],
      related: ['VT-203'],
    },
  },
  {
    id: 'VT-709',
    name: 'Honeycomb',
    exportNames: ['Honeycomb'],
    kind: 'pattern',
    meta: {
      category: 'concept-framework',
      summary: '육각 셀 다면 속성 표현',
      dataShape: ['concept', 'comparison'],
      primitives: ['grid'],
      aliases: ['UX honeycomb', 'hexagon cluster'],
      useWhen: ['다면 속성/기준을 육각 셀로 제시할 때'],
      avoidWhen: ['정량 축 비교는 Radar(VT-511) 사용'],
      tags: ['framework'],
      related: ['VT-511'],
    },
  },
  {
    id: 'VT-710',
    name: 'Spectrum Slider',
    exportNames: ['SpectrumSlider'],
    kind: 'pattern',
    meta: {
      category: 'concept-framework',
      summary: '대립 양극 축 위 위치 표시',
      dataShape: ['comparison', 'ranking'],
      primitives: ['axis', 'node'],
      aliases: ['continuum', 'opposing-axis scale'],
      useWhen: ['대립하는 양극 축 위에 성향/성숙도 위치를 표시할 때'],
      avoidWhen: ['2축 4분면 배치는 Quadrant(VT-702) 사용'],
      tags: ['framework'],
      related: ['VT-702'],
    },
  },
];
